name: CI

on:
  pull_request:
    branches: [main]

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
      - name: Audit @qbjs/core dependencies
        # when a vulnerability is found that fails the build, try to use
        # `pnpm audit --fix` which will override version within
        # package.json#pnpm.overrides to patched version.
        # Second, use package.json#pnpm.auditConfig.ignoreCves if harmless.
        run: pnpm audit:core

  check-types:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
      - name: Type Check @qbjs/core
        run: pnpm checktypes:core
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
      - name: Lint
        run: pnpm format:core

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
      - name: Test @qbjs/core
        run: pnpm test:core

# stops workflows in progress if a new commit is added to PR
# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true
